# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ric0LVcuLkYbUAIaFxT6e0BCNAE8WRjZ
"""

"""
app.py

Main entrypoint for the 🇧🇭 Bahrain Statistical AI Agent.

- Loads pre-aggregated CSVs from data/bahrain_master/
- Creates a BahrainStatsAgent instance
- Exposes a Gradio chat UI

You do NOT need to change this file when you update the data.
Just regenerate the CSVs in data/bahrain_master/ and restart.
"""

import os
import gradio as gr

# If you turned your notebook logic into a module, this import should work:
# Make sure you have a package folder `bahrain_agent/` with __init__.py and agent.py
from bahrain_agent.agent import BahrainStatsAgent


# ------------ CONFIG ------------

# Folder where your 8 master CSVs live
DATA_PATH = os.getenv("BAHRAIN_DATA_PATH", "data/bahrain_master")

# If you later add an LLM wrapper, you can also read OPENAI_API_KEY here, etc.
# For now we’ll just use the rule-based/statistical agent.


# ------------ INIT AGENT ------------

# Create a single global agent instance that stays in memory
agent = BahrainStatsAgent(data_path=DATA_PATH)


# ------------ CHAT HANDLER ------------

def chat_with_agent(message: str, history):
    """
    Gradio ChatInterface callback.

    Parameters
    ----------
    message : str
        The latest user message.
    history : list
        Chat history (we don’t actually use it in the logic,
        but Gradio passes it in).

    Returns
    -------
    str
        The agent's reply as plain text.
    """
    # Core logic: delegate to your agent
    answer = agent.answer_question(message)
    return answer


# ------------ BUILD UI ------------

demo = gr.ChatInterface(
    fn=chat_with_agent,
    title="🇧🇭 Bahrain Statistical AI Agent",
    description=(
        "Ask about Bahrain's labour, occupations, households, population density, "
        "housing units, students, teachers, and higher education.\n\n"
        "Examples:\n"
        "- Summarize the labour market in 2022\n"
        "- What are the most common occupations?\n"
        "- Describe households and population density by governorate\n"
        "- Give an overview of higher education students"
    ),
    examples=[
        "Summarize the labour market in 2022",
        "What are the most common occupations?",
        "Describe households and population density by governorate",
        "Give an overview of higher education students",
    ],
)


# ------------ MAIN ------------

if __name__ == "__main__":
    # You can expose this on a specific host/port if you like:
    # demo.launch(server_name="0.0.0.0", server_port=7860)
    demo.launch()

