# -*- coding: utf-8 -*-
"""data_layer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ric0LVcuLkYbUAIaFxT6e0BCNAE8WRjZ
"""

"""
data_layer.py

Loads all Bahrain master CSVs into a typed DataRepository.
This is the ONLY place that touches CSV files.

If a file is missing, an empty DataFrame is used and a warning is printed.
"""

from dataclasses import dataclass
from typing import Optional
import os
import pandas as pd


@dataclass
class DataRepository:
    labour_master: pd.DataFrame
    occupation_workers: pd.DataFrame
    households: pd.DataFrame
    population_density: pd.DataFrame
    housing_units: pd.DataFrame
    students: pd.DataFrame
    teachers: pd.DataFrame
    higher_education: pd.DataFrame


def _safe_read_csv(path: str) -> pd.DataFrame:
    """Read CSV if it exists, otherwise return an empty DataFrame."""
    if not os.path.exists(path):
        print(f"[bahrain_agent] WARNING: CSV not found: {path} (using empty DataFrame)")
        return pd.DataFrame()
    try:
        df = pd.read_csv(path)
    except Exception as e:
        print(f"[bahrain_agent] ERROR reading {path}: {e} (using empty DataFrame)")
        df = pd.DataFrame()
    return df


def _standardize_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Normalize column names to lowercase snake_case.
    Also try to standardize 'Year'/'year ' etc -> 'year',
    'Governorate'/'gov_name' -> 'governorate', etc.
    Adjust mapping if your real columns differ.
    """
    if df.empty:
        return df

    # Lowercase and strip whitespace
    df = df.rename(columns={c: c.strip() for c in df.columns})
    df.columns = [c.strip().lower() for c in df.columns]

    # Common renames
    rename_map = {}
    for col in list(df.columns):
        if col in ("governorate_name", "gov_name"):
            rename_map[col] = "governorate"
        if col in ("nationality_group", "nat_group"):
            rename_map[col] = "nationality"
        if col in ("total_workers", "workers_total"):
            rename_map[col] = "total_workers"
        if col in ("no_of_households", "number_of_households"):
            rename_map[col] = "households"
        if col in ("no_of_units", "number_of_units"):
            rename_map[col] = "units"
        if col in ("no_of_students", "number_of_students"):
            rename_map[col] = "students"
        if col in ("no_of_teachers", "number_of_teachers"):
            rename_map[col] = "teachers"

    if rename_map:
        df = df.rename(columns=rename_map)

    return df


def load_all_data(base_path: str = "data/bahrain_master") -> DataRepository:
    """
    Load all 8 master CSVs from base_path and return a DataRepository.

    Expected filenames (you can change these if needed, but keep them consistent):
    - labour_master.csv
    - occupation_workers.csv
    - households.csv
    - population_density.csv
    - housing_units.csv
    - students.csv
    - teachers.csv
    - higher_education.csv
    """
    def p(name: str) -> str:
        return os.path.join(base_path, name)

    labour_master = _standardize_columns(_safe_read_csv(p("labour_master.csv")))
    occupation_workers = _standardize_columns(_safe_read_csv(p("occupation_workers.csv")))
    households = _standardize_columns(_safe_read_csv(p("households.csv")))
    population_density = _standardize_columns(_safe_read_csv(p("population_density.csv")))
    housing_units = _standardize_columns(_safe_read_csv(p("housing_units.csv")))
    students = _standardize_columns(_safe_read_csv(p("students.csv")))
    teachers = _standardize_columns(_safe_read_csv(p("teachers.csv")))
    higher_education = _standardize_columns(_safe_read_csv(p("higher_education.csv")))

    return DataRepository(
        labour_master=labour_master,
        occupation_workers=occupation_workers,
        households=households,
        population_density=population_density,
        housing_units=housing_units,
        students=students,
        teachers=teachers,
        higher_education=higher_education,
    )

