# -*- coding: utf-8 -*-
"""describe_layer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ric0LVcuLkYbUAIaFxT6e0BCNAE8WRjZ
"""

"""
describe_layer.py

Turns DataRepository + query_layer outputs into human-readable text.
No direct CSV access here, only structured data from query_layer.
"""

from typing import Optional
from textwrap import indent

from .data_layer import DataRepository
from .query_layer import (
    get_workers_by_year,
    get_top_occupations,
    get_households_by_governorate,
    get_latest_density,
    get_housing_units_summary,
    get_students_summary,
    get_teachers_summary,
    get_higher_education_summary,
)


def describe_labour_market(repo: DataRepository, year: Optional[int]) -> str:
    workers = get_workers_by_year(repo, year)
    top_occ = get_top_occupations(repo, year, top_n=3)

    if workers.empty and top_occ.empty:
        if year is None:
            return "I couldn't find any labour market data in the current dataset."
        return f"I couldn't find labour market data for {year} in the current dataset."

    lines = []
    if year is not None:
        lines.append(f"Labour market overview for {year} in Bahrain:\n")
    else:
        lines.append("Labour market overview for Bahrain:\n")

    if not workers.empty:
        total = int(workers["total_workers"].sum())
        lines.append(f"- Total recorded workers: {total:,}")

        top_nat = workers.iloc[0]
        lines.append(
            f"- Largest nationality group: {top_nat['nationality']} "
            f"with {int(top_nat['total_workers']):,} workers"
        )

    if not top_occ.empty:
        lines.append("\nTop 3 occupations by number of workers:")
        for _, row in top_occ.iterrows():
            lines.append(
                f"- {row['main_occupation']}: {int(row.iloc[1]):,} workers"
            )

    return "\n".join(lines)


def describe_governorates(repo: DataRepository) -> str:
    households = get_households_by_governorate(repo)
    density = get_latest_density(repo)

    if households.empty and density.empty:
        return "I couldn't find households or population density data in the current dataset."

    lines = []
    lines.append("Households and population density by governorate:\n")

    if not households.empty:
        lines.append("Households by governorate:")
        # Show top governorates
        top = households.head(10)
        for _, row in top.iterrows():
            gov = row.get("governorate", "Unknown governorate")
            val = row.iloc[-1]
            nat = row.get("nationality")
            if nat:
                lines.append(f"- {gov} ({nat}): {int(val):,} households")
            else:
                lines.append(f"- {gov}: {int(val):,} households")

    if not density.empty:
        latest_year = int(density["year"].max()) if "year" in density.columns else None
        if latest_year:
            lines.append(f"\nLatest population density data (year {latest_year}):")
        else:
            lines.append("\nLatest population density data:")

        for _, row in density.iterrows():
            gov = row.get("governorate", "Unknown governorate")
            pop = row.get("population")
            dens = row.get("density")
            if pop is not None and dens is not None:
                lines.append(f"- {gov}: population {int(pop):,}, density {dens} people/km²")
            elif pop is not None:
                lines.append(f"- {gov}: population {int(pop):,}")
            else:
                lines.append(f"- {gov}: density data available")

    return "\n".join(lines)


def describe_housing_units(repo: DataRepository) -> str:
    df = get_housing_units_summary(repo)
    if df.empty:
        return "I couldn't find housing units data in the current dataset."

    lines = ["Housing units by governorate and type:\n"]
    top = df.head(15)
    for _, row in top.iterrows():
        gov = row.get("governorate", "Unknown governorate")
        htype = row.get("housing_type", "All types")
        units = row.iloc[-1]
        lines.append(f"- {gov} – {htype}: {int(units):,} units")

    return "\n".join(lines)


def describe_students(repo: DataRepository) -> str:
    df = get_students_summary(repo)
    if df.empty:
        return "I couldn't find students data in the current dataset."

    lines = ["Students overview by sector and level:\n"]
    top = df.head(15)
    value_col = "students"
    for _, row in top.iterrows():
        sectors = []
        for c in ["sector", "school_type"]:
            if c in row and isinstance(row[c], str):
                sectors.append(row[c])
        level = row.get("level", "All levels")
        count = int(row[value_col])
        if sectors:
            lines.append(f"- {' / '.join(sectors)} – {level}: {count:,} students")
        else:
            lines.append(f"- {level}: {count:,} students")

    return "\n".join(lines)


def describe_teachers(repo: DataRepository) -> str:
    df = get_teachers_summary(repo)
    if df.empty:
        return "I couldn't find teachers data in the current dataset."

    lines = ["Teachers overview by school type and level:\n"]
    top = df.head(15)
    value_col = "teachers"
    for _, row in top.iterrows():
        desc_parts = []
        for c in ["school_type", "sector"]:
            if c in row and isinstance(row[c], str):
                desc_parts.append(row[c])
        level = row.get("level", "All levels")
        count = int(row[value_col])
        if desc_parts:
            lines.append(f"- {' / '.join(desc_parts)} – {level}: {count:,} teachers")
        else:
            lines.append(f"- {level}: {count:,} teachers")

    return "\n".join(lines)


def describe_higher_education(repo: DataRepository) -> str:
    df = get_higher_education_summary(repo)
    if df.empty:
        return "I couldn't find higher education data in the current dataset."

    lines = ["Higher education students by sector and programme:\n"]
    top = df.head(15)
    value_col = "students"
    for _, row in top.iterrows():
        sector = row.get("sector", "All sectors")
        prog = row.get("academic_programme", row.get("level", "All programmes"))
        count = int(row[value_col])
        lines.append(f"- {sector} – {prog}: {count:,} students")

    return "\n".join(lines)

