# -*- coding: utf-8 -*-
"""nlu_router.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ric0LVcuLkYbUAIaFxT6e0BCNAE8WRjZ
"""

"""
nlu_router.py

Simple rule-based NLU for:
- Intent classification
- Year extraction

This is deliberately lightweight so you don't depend on an LLM.
"""

from typing import Optional
import re


INTENT_KEYWORDS = {
    "labour_overview": [
        "labour", "labor", "employment", "unemployment", "workforce",
        "jobs", "workers", "labour market", "labor market",
    ],
    "top_occupations": [
        "top occupation", "most common jobs", "most common occupations",
        "top jobs", "popular jobs", "occupation",
    ],
    "households": [
        "household", "households", "family", "families",
    ],
    "density": [
        "population density", "densely populated", "density",
    ],
    "housing_units": [
        "housing units", "dwellings", "apartments", "houses",
        "residential units",
    ],
    "students": [
        "students", "school enrollment", "pupils", "enrolment",
    ],
    "teachers": [
        "teachers", "teaching staff", "instructors",
    ],
    "higher_education": [
        "higher education", "university", "universities", "college",
        "tertiary education",
    ],
}


def classify_intent(question: str) -> str:
    """
    Very simple keyword-based intent classification.

    Returns one of:
    - 'labour_overview'
    - 'top_occupations'
    - 'households'
    - 'density'
    - 'housing_units'
    - 'students'
    - 'teachers'
    - 'higher_education'
    Or 'unknown' if nothing matches.
    """
    q = question.lower()

    for intent, keywords in INTENT_KEYWORDS.items():
        for kw in keywords:
            if kw in q:
                return intent

    # Mild heuristic: if it mentions "population" and not "density",
    # treat as 'density' intent (since we have population_density table).
    if "population" in q:
        return "density"

    return "labour_overview" if "unemployment" in q or "employment" in q else "unknown"


def extract_year(question: str, default_year: Optional[int] = None) -> Optional[int]:
    """
    Extracts the first 4-digit year between 1900 and 2100 from the question.
    If none is found, returns default_year.
    """
    q = question
    years = re.findall(r"\b(19[0-9]{2}|20[0-9]{2}|2100)\b", q)
    if years:
        try:
            return int(years[0])
        except ValueError:
            pass
    return default_year

