# -*- coding: utf-8 -*-
"""query_layer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ric0LVcuLkYbUAIaFxT6e0BCNAE8WRjZ
"""

"""
query_layer.py

Low-level analytical functions that operate on DataRepository
and return DataFrames (or similar structured objects), NOT text.

These functions are used by the describe_layer.
"""

from typing import Optional
import pandas as pd

from .data_layer import DataRepository


def _safe_filter_year(df: pd.DataFrame, year: Optional[int]) -> pd.DataFrame:
    if df.empty or year is None or "year" not in df.columns:
        return df
    return df[df["year"] == year]


# ---------- Labour & Occupations ----------

def get_workers_by_year(repo: DataRepository, year: Optional[int]) -> pd.DataFrame:
    """
    Returns a dataframe grouped by nationality with total workers for a given year.
    Expected columns in labour_master: ['year', 'nationality', 'total_workers']
    """
    df = repo.labour_master
    if df.empty:
        return df

    df = _safe_filter_year(df, year)
    if df.empty:
        return df

    if "nationality" not in df.columns or "total_workers" not in df.columns:
        return pd.DataFrame()

    grouped = df.groupby("nationality", as_index=False)["total_workers"].sum()
    return grouped.sort_values("total_workers", ascending=False)


def get_top_occupations(
    repo: DataRepository,
    year: Optional[int],
    top_n: int = 5
) -> pd.DataFrame:
    """
    Returns top N occupations by number of workers for a given year.
    Expected columns in occupation_workers:
        ['year', 'main_occupation', 'nationality', 'occupation_workers']
    """
    df = repo.occupation_workers
    if df.empty:
        return df

    df = _safe_filter_year(df, year)
    if df.empty:
        return df

    if "main_occupation" not in df.columns:
        return pd.DataFrame()

    value_col = "occupation_workers" if "occupation_workers" in df.columns else None
    if value_col is None:
        return pd.DataFrame()

    df_sorted = df.sort_values(value_col, ascending=False)
    return df_sorted.head(top_n)[["main_occupation", value_col]]


# ---------- Households & Population Density ----------

def get_households_by_governorate(repo: DataRepository) -> pd.DataFrame:
    """
    Group households by governorate and nationality (if available).
    Expected columns: ['governorate', 'nationality', 'households']
    """
    df = repo.households
    if df.empty:
        return df

    if "governorate" not in df.columns:
        return pd.DataFrame()

    value_col = "households" if "households" in df.columns else None
    if value_col is None:
        return pd.DataFrame()

    group_cols = ["governorate"]
    if "nationality" in df.columns:
        group_cols.append("nationality")

    grouped = df.groupby(group_cols, as_index=False)[value_col].sum()
    return grouped.sort_values(value_col, ascending=False)


def get_latest_density(repo: DataRepository) -> pd.DataFrame:
    """
    Returns population density info for the latest available year.
    Expected columns: ['year', 'governorate', 'population', 'density'] (density optional).
    """
    df = repo.population_density
    if df.empty or "year" not in df.columns:
        return df

    latest_year = df["year"].max()
    df_latest = df[df["year"] == latest_year]

    return df_latest


# ---------- Housing Units ----------

def get_housing_units_summary(repo: DataRepository) -> pd.DataFrame:
    """
    Group housing units by governorate and housing_type if available.
    Expected columns: ['governorate', 'housing_type', 'units']
    """
    df = repo.housing_units
    if df.empty:
        return df

    if "governorate" not in df.columns:
        return pd.DataFrame()

    value_col = "units" if "units" in df.columns else None
    if value_col is None:
        return pd.DataFrame()

    group_cols = ["governorate"]
    if "housing_type" in df.columns:
        group_cols.append("housing_type")

    grouped = df.groupby(group_cols, as_index=False)[value_col].sum()
    return grouped.sort_values(value_col, ascending=False)


# ---------- Students ----------

def get_students_summary(repo: DataRepository) -> pd.DataFrame:
    """
    Group students by sector and level if available.
    Expected columns: ['year', 'sector', 'level', 'students']
    """
    df = repo.students
    if df.empty:
        return df

    value_col = "students" if "students" in df.columns else None
    if value_col is None:
        return pd.DataFrame()

    group_cols = []
    for c in ["sector", "level", "school_type"]:
        if c in df.columns:
            group_cols.append(c)

    if not group_cols:
        return pd.DataFrame()

    grouped = df.groupby(group_cols, as_index=False)[value_col].sum()
    return grouped.sort_values(value_col, ascending=False)


# ---------- Teachers ----------

def get_teachers_summary(repo: DataRepository) -> pd.DataFrame:
    """
    Group teachers by school_type and level if available.
    Expected columns: ['year', 'school_type', 'level', 'teachers']
    """
    df = repo.teachers
    if df.empty:
        return df

    value_col = "teachers" if "teachers" in df.columns else None
    if value_col is None:
        return pd.DataFrame()

    group_cols = []
    for c in ["school_type", "level", "sector"]:
        if c in df.columns:
            group_cols.append(c)

    if not group_cols:
        return pd.DataFrame()

    grouped = df.groupby(group_cols, as_index=False)[value_col].sum()
    return grouped.sort_values(value_col, ascending=False)


# ---------- Higher Education ----------

def get_higher_education_summary(repo: DataRepository) -> pd.DataFrame:
    """
    Group higher education students by sector and academic_programme.
    Expected columns: ['year', 'sector', 'academic_programme', 'students']
    """
    df = repo.higher_education
    if df.empty:
        return df

    value_col = "students" if "students" in df.columns else None
    if value_col is None:
        return pd.DataFrame()

    group_cols = []
    for c in ["sector", "academic_programme", "level"]:
        if c in df.columns:
            group_cols.append(c)

    if not group_cols:
        return pd.DataFrame()

    grouped = df.groupby(group_cols, as_index=False)[value_col].sum()
    return grouped.sort_values(value_col, ascending=False)

